### ISSUE TITLE
retry db connection while initializing migration operation

### ISSUE THREAD

**Issue by mstrYoda** [authzed/spicedb#1070]
Hi all 👋 

We are using spicedb and we are also enabled istio service mesh in our clusters. Because of container orders istio starts after the spicedb container and this causes spicedb container to not do any network operation until istio becomes ready.

It would be nice to add backoff retry functionality to migrate commands: https://github.com/authzed/spicedb/blob/main/pkg/cmd/migrate.go#L63

WDYT about it?

**Comment by vroldanbet** [comment]
👋🏻 @mstrYoda can you elaborate a bit more on your setup? Are you running a container with `spicedb migrate`, and it fails because the data-plane sidecar (I presume this is envoy for Istio), which is a container in the pod, hasn't started yet?

For migrations we would suggest using the spicedb operator, which handles migration for you.

Is there any reason you need it only for `spicedb migrate` and not for `spicedb serve`?

Otherwise I see no reason why we couldn't add retries

**Comment by mstrYoda** [comment]
> 👋🏻 @mstrYoda can you elaborate a bit more on your setup? Are you running a container with `spicedb migrate`, and it fails because the data-plane sidecar (I presume this is envoy for Istio), which is a container in the pod, hasn't started yet?
> 
> I thought of [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/), but I guess that wouldn't work because the istio sidecar wouldn't have started until the init container completes. I thought of init containers because Kube would retry your container until it succeeds.
> 
> For migrations we would suggest using the spicedb operator, which handles migration for you.
> 
> Is there any reason you need it only for `spicedb migrate` and not for `spicedb serve`?
> 
> Otherwise I see no reason why we couldn't add retries

Hi @vroldanbet 👋 Thank you for your response. Actually, that is the exact situation. Because of istio-proxy sideacr container is not started before spicedb, pod is not able to go network. So we can actually add retry to all of the authz commands like migrate/serve etc.

It would also be nice to have that with an argument like `initialStartBackoffLimit`. WDYT about it?

**Comment by vroldanbet** [comment]
@mstrYoda got it, yeah I think it would make sense to adjust all datastores not to fail immediately, but make several attempts to connect with a configurable backoff, not too long so that eventually the pod restarts and makes evident to the operator something is not quite right.

Would you be up for contributing the patch?

**Comment by mstrYoda** [comment]
> @mstrYoda got it, yeah I think it would make sense to adjust all datastores not to fail immediately, but make several attempts to connect with a configurable backoff, not too long so that eventually the pod restarts and makes evident to the operator something is not quite right.
> 
> Would you be up for contributing the patch?

Yeap I would love to contribute by adding backoff retry 👍

**Comment by oursland** [comment]
You can configure the Istio option [`meshConfig.defaultConfig.holdApplicationUntilProxyStarts`](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig) to `true` to block application starts until the sidecar proxy is loaded.

I do not know why this is not the default configuration as many/most applications will need network access and that isn't available if the application launches before the proxy has established the netfilter rules.

**Comment by vroldanbet** [comment]
@oursland thanks for sharing! Given there is an alternative, I'll proceed to close this one. Y'all feel free to reopen if there are use-cases outside of the one mentioned here with sidecars.
