### ISSUE TITLE
Add support for getting "earliest" available ZedToken

### ISSUE THREAD

**Issue by jason-who-codes** [authzed/spicedb#1168]
[WatchRequest](https://buf.build/authzed/api/docs/main:authzed.api.v1#authzed.api.v1.WatchRequest) accepts an `optional_start_cursor` but does not document the behavior if the cursor is not provided (it would be helpful to clarify this in the docs). If I'm [reading this right](https://github.com/authzed/spicedb/blob/main/internal/services/v1/watch.go#L53-L59) SpiceDB will just generate a "current" revision and start the watch from there. So if you don't already have a ZedToken, there is no way to do a retroactive `watch`.

When starting a new "watcher" process, it would be ideal to be able to specify that the watch should return all transactions since the beginning of time. However, I recognize that GC limits the window of time that a transaction can be available for watch (i.e. currently 24 hours by default). It would be useful to have a mechanism (new gRPC endpoint?) to ask SpiceDB for a ZedToken representing the "oldest" point in time that should still be visible within the GC window. This would allow a "new" watcher to get a token to use as input on the WatchRequest. 

Such an endpoint might also support getting a "current" ZedToken (to replace the idiom of making a bogus `CheckPermission` request in order to get a token) or even getting a ZedToken approximating a particular wall-clock time.

In combination with #1162 this would enable building a robust "watcher" process, which can retroactively stream all events still within the GC window (by getting an "oldest" ZT if it doesn't have a ZT stored from prior invocations) and can also auto-detect if it has "missed" data after an extended outage (get a ZT for the oldest data within GC window, and compare it to the ZT of the last-seen transaction from a prior watch request).

**Comment by ecordell** [comment]
ZedTokens are supposed to be opaque, because they [can and do change](https://github.com/authzed/spicedb/pull/1153) format periodically. I think it's unlikely we'll want to  make them externally comparable any time soon, if ever.

> When starting a new "watcher" process, it would be ideal to be able to specify that the watch should return all transactions since the beginning of time. 

If ReadRelationships were [resumable](https://github.com/authzed/spicedb/issues/1163), as you've also suggested, you could bootstrap a new watcher with a read of all existing relationships, then grab the zedtoken from the ReadRelationships response when you're done, and start your watch from there. List+Watch is a fairly common pattern that seems reasonable for us to support (kubernetes uses the same model, for example).

Does that work for your use case? If not, could you clarify what you would do with the older watch responses? I'm unclear what you would do with them if they don't reach back to the beginning.

**Comment by jason-who-codes** [comment]
That's fair, List+Watch would reduce the need for being able to start a watch from the earliest (which anyways has questionable value due to GC). However, I think it would still be beneficial for a watcher to be able to compare it's "last seen" ZT against the age of GC window, to auto-detect if there has potentially been some event loss when recovering from a crash

**Comment by jason-who-codes** [comment]
I performed some experimentation and found that SpiceDB already reports an error if a watch client attempts to perform a watch with "too old" of a timestamp:
> Watch got onError: INTERNAL: watch error: ERROR: batch timestamp 1676564322.048753796,0 must be after replica GC threshold 1676843193.413931169,0 (SQLSTATE XXUUU)

**Comment by jason-who-codes** [comment]
Given that, I think the only remaining request here is to update the documentation on [WatchRequest](https://buf.build/authzed/api/docs/main:authzed.api.v1#authzed.api.v1.WatchRequest).`optional_start_cursor` to clarify that the watch will start from the "current" revision if no value is provided.

**Comment by josephschorr** [comment]
@jason-who-codes https://github.com/authzed/api/blob/main/authzed/api/v1/watch_service.proto#L34 if you'd like to make that change
