### ISSUE TITLE
BUG: After upgrading to 1.21 api /permissions/resources returns same items multiple times

### ISSUE THREAD

**Issue by muntdan** [authzed/spicedb#1358]
I reverted back to 1.20 and they are ok again.
FIY: I am using postgres store.

**Comment by josephschorr** [comment]
@muntdan LookupResources was never intended to not return duplicates; we did filtering locally previously as a side effect of not fully streaming the results. Moving forward, however, all results are fully streamed, which means this kind of filtering is no longer applicable. It is up to the caller to filter duplicates as they see fit.

**Comment by muntdan** [comment]
If you indulge me I would like to add some details and some fallow-up questions:

My structure is as fallows: [customer1] -> [fleet1] -> [fleet2] (as a child fleet)
                                                                   [fleet1] -> car1 
                                           [customer1] -> user1
And the call I do basically asks for all fleets the user1 has access to.
This now answers with 4 of fleet1.

So my questions is:
1) Is this indeed the intended behavior on the new version ?
2) Having only 3 tuple in db with fleet1 why is there a 4th also in the answer ?
3) What scenario/type or request could having it multiple times help ?
4) What other method that could be used for the basic request "give me all entity of type X for user Y" that returns only once the items ?
5) Is this new behavior documented somewhere in regards to the duplicates ?

**Comment by josephschorr** [comment]
@muntdan I'm having trouble following your example, but I'll try to answer as best as I can

1. It may not be the intended behavior in v1.21, but returning duplicates will certainly be the behavior in v1.22 if multiple paths can be followed to find the same resource
2. Unclear, but as I said, even if this isn't the intended behavior now, starting in the next version duplicates **will** be returned if a resource is reachable through multiple paths for the same user
3. Consider the following:

definition user {}

definition organization {
  relation admin: user
}

definition resource {
  relation editor: user
  relation organization: organization
  permission edit = editor + organization->admin
}

with relationships

resource:someresource#editor@user:tom
resource:someresource#organization@organization:someorg
organization:someorg#admin@user:tom

In the above example, `user:tom` is both the direct `editor` of the resource and an `admin` of the organization, which grants him `edit` permission on the resource twice.

In v1.22, a request for all the resources on which `user:tom` has `edit` permission may return `resource:someresource` twice, because there are *two* paths to that resource+permission for the same user.

4. Filter on the client side. 

Deduplication would require SpiceDB to keep the entire list of found resources in-memory while returning. This is what we previously did in v1.20 and earlier, but doing so meant that result sets that numbered in the hundreds of thousands or even millions would quickly eat up a significant chunk of memory and cause massive performance problems. Starting in v1.22, LookupResources also supports cursors and limits, which means SpiceDB can now return pages of results. This, in turn, means we *cannot* deduplicate because one page doesn't necessarily know which results were returned in the previous page. It is up to the caller to decide what to do in terms of deduplication.

7. This was always the intended behavior; the deduplication was just a "side effect" of LookupResources not being fully streaming. We will add additional documentation to the API to make it clear that it can (and will) return duplicates

**Comment by muntdan** [comment]
Ok , I understood they should appear multiple times equal to the paths it can reach the entity.
But in my case there is only 2 paths and the answer returns it 4 times:
![image](https://github.com/authzed/spicedb/assets/105269340/1177826a-7d8b-458a-a3b1-7eb9e4d07e69)
So are you sure there is no bug ?

**Comment by josephschorr** [comment]
As stated above, I'm not 100% sure, but as this code was completely rewritten in V1.22 *and* duplicates are expected regardless, this isn't really a "bug"

**Comment by jzelinskie** [comment]
@muntdan can you create a minimal schema and relationship set in the [playground](https://play.authzed.com) that reproduces this issue? I think that'd be the most useful way for us to determine why you're seeing 4 results when you think there should be only two paths.

**Comment by muntdan** [comment]
Hi @jzelinskie this is the playground: https://play.authzed.com/s/cCvPK8QYl0oP/relationships.
Let me know if you need anything else.

**Comment by muntdan** [comment]
Is this fix  https://github.com/authzed/spicedb/pull/1386 for my issues also?
