### ISSUE TITLE
Max connections open flag does not work

### ISSUE THREAD

**Issue by nate-kis** [authzed/spicedb#2019]
### What platforms are affected?

linux

### What architectures are affected?

amd64

### What SpiceDB version are you using?

V1.32.0

### Steps to Reproduce

Have the following argument on command line:

`--datastore-conn-max-open=10`

### Expected Result

Connection limits are limited to the setting in the flag and cannot exceed the amount of connections

We have a max replicas of 10, and our database has a max connection of 200. But with 10 max replicas and 10 max connections flag, we sometimes get too many connections used in our database, when this is the only service that connects to that database.

We also get a message the flag is deprecated, but can't find any documentation on the spicedb site that has what to use instead, it still references `--datastore-conn-max-open` 

### Actual Result

1. I get an error on startup saying `Flag --datastore-conn-max-open has been deprecated, connection pooling has been split into read and write pools`
2. Despite having this value set to 10, and have maximum 10 replicas, we get to too many connections used (our database has a max of 200)

**Comment by tstirrat15** [comment]
The deprecation warning is indicating that this flag has been superseded by these two:
```
--datastore-conn-pool-write-max-open int                           number of concurrent connections open in a remote datastore's connection pool (default 10)
--datastore-conn-pool-read-max-open int                            number of concurrent connections open in a remote datastore's connection pool (default 20)
```
The numbers don't entirely line up, but can you try using the read + write flags rather than the old flag?

Also keep in mind that this is on the individual SpiceDB node, so if you're running multiple nodes and/or have autoscaling in place, you need to account for that.

**Comment by bradengroom** [comment]
I'm not sure which DB you're using, but it may also be appropriate to consider using a connection pooler (e.g. pgbouncer for postgres)

**Comment by vroldanbet** [comment]
I don't think this is the reason you are observing those excess connections, but I'll leave it here for reference, since there was a recent bug on how min connections was handled: https://github.com/authzed/spicedb/pull/1747

Aside from the read-and-write connection pools, connections are opened for other reasons, outside of those pools:
- [datastore health checks](https://github.com/authzed/spicedb/blob/3c57fddf4f745f8883204ccfbdd97fc7c15b6a3a/internal/datastore/postgres/postgres.go#L645-L649): that will be at least 1 extra connection used every time the health check is run
- Watch API calls: in the case of CockroachDB, [a new connection will be created per Watch API call](https://github.com/authzed/spicedb/blob/3d8c1aa595cd315750e0e537ac81a34758fc5204/internal/datastore/crdb/watch.go#L91-L96).

We recommend:
- using the read/write conn pool specific flags (`spicedb serve --help` should describe those flags)
- do not configure pools to max out the database's available connections: leave some headroom for things like health checks.

Also somewhat related, as of https://github.com/authzed/spicedb/pull/1994 there should be better support for connection poolers like pgbouncer

**Comment by nate-kis** [comment]
i did use pgBouncer initially, but it was transactional and not supported by spicedb.

I've updated to use what @tstirrat15 referenced and the too many connections issue has been resolved.
