### ISSUE TITLE
Why not database/sql pattern?

### ISSUE THREAD

**Issue by RajeshArista** [authzed/spicedb#504]
It would be easy to integrate our custom datastore with spiceDB if we implement the database/sql design pattern. https://eli.thegreenplace.net/2019/design-patterns-in-gos-databasesql-package/#registering-drivers. We could register our own datastore without much code churn into spicedb.

**Comment by jzelinskie** [comment]
Hey there! This is a great question.

We've implemented this pattern in lots of Go programs over the years. However, I don't think it's ever ended up proving itself particularly useful for this use case.

Because datastore implementations end up being trickier than one might first think due to subtle behavior changes from the the rest of the codebase, we'd prefer to collaborate with the community to contribute work like this upstream. By keeping things upstream, we can ensure that we're staying considerate of the users leveraging said datastore and can build test suites that ensure we aren't breaking anyone with any subtle changes.

I think if we were to one day be swarming in datastore implementations or struggle to keep some maintained, then this could be worth considering.

Let me know whatcha think!

**Comment by jfrabaute** [comment]
Hi,

Thanks for the feedback.

One of the reasons to expose a registry and allow to register external datastores is because some implementations cannot be public for the datastore.
This can be the case with some DB where the code is not public, and the corresponding implementation cannot be public.
In this case, being able to register a datastore from an external package makes spicedb more reusable and it increases adoption.

Another reason is that, even for datastore implementations that can be public, having all of them maintained in the base repo seems like a lot of work, especially if the original author cannot maintain it.
In this case, the datastore implemented in the separate repo can be pinned to a specific spicedb version and not support the new ones and it allows spicedb to continue to evolve regardless of those non-maintained datastores.

Switching to this pattern does not change the existing datastores in this repo which can still be maintained and managed the same way they are as of today.
It adds the flexibility to add external datastores that can be maintained externallly by the community, as well as private datastores because the code of the implementation cannot be public.

We'd be happy to send a PR to do the change to registration similar to the database/sql pattern, if this is something you'd be ok to merge.

Happy to discuss more.

Thanks.

**Comment by jzelinskie** [comment]
At Authzed, we've been thinking about fleshing out a more generic proposal for extensions/plugins to SpiceDB.

I think ultimately this will include the registration pattern for various integration points into SpiceDB.
We think the first pass of integration points are gRPC Services, gRPC Middleware, SpiceDB Datastores.

We want to make sure everything is versioned and sane for folks debug, which would require a bit more of a proposal than just an issue for adding the registration pattern.

We'll gather up some requirements in addition to the ones in this thread and post a proposal and linked to this issue.

**Comment by josephschorr** [comment]
Based on the current customization necessary for each datastore implementation, we feel its unlikely in the near future that simply implementing the database/sql pattern would allow for a working and, more importantly, performant, backend for SpiceDB

To that end we're going to close this issue for the time being, but if this situation changes or significant interest comes up in the future for a viable solution here, feel free to reopen
