### ISSUE TITLE
Health checks should fail if datastore becomes unavailable

### ISSUE THREAD

**Issue by wasifaleem** [authzed/spicedb#692]
As indicated in the [k8s example](https://github.com/authzed/spicedb/blob/main/examples/k8s/example.yaml#L145), we're using the `grpc_health_probe` to monitor the spicedb health. But turns out the health check still returns status as `SERVING` if the datastore becomes abruptly unavailable. 

I verified this behavior by starting up a local spicedb + postgresql container, the initial health check succeeds. But when i kill the postgresql container, the expectation is for the health check to fail but nevertheless it still succeeds.

**Comment by josephschorr** [comment]
This is by design: we ensure that SpiceDB is talking to a valid and working datastore instance on startup, but explicitly do not continue checking the status after that point. This is done because of the following scenario: Imagine that the underlying database goes into failover: if SpiceDB was checking the status of the database as part of the continuous health check, as soon as the database went into failover (and was thus temporarily out of service), *all* SpiceDB pods would be reported as unhealthy, completely taking the entire service out of production. When the database came back into service, it would take a small but significant amount of time for the SpiceDB service to redeploy and scale, thus resulting in a longer outage.

The recommendation is to have distinct health checks for the underlying database, and to alert based on those as well.

**Comment by wasifaleem** [comment]
I get your reasoning. However, there are valid scenarios where this design affects availability of services that depend on spicedb and deeper/dependency health checks are needed to react (heal/restart/alert) to such scenarios. 

Some example scenarios are datastore endpoint changing due a automated snapshot recovery or automated datastore credentials rotations or chaos testing. With the current design, spicedb will still report healthy accepting traffic, but still failing to process requests. There is no way for us to auto heal in these scenarios from the existing health check which is deep enough to ensure that spicedb is running and responding but not deep enough to ensure it is responding correctly.

**Comment by josephschorr** [comment]
> Some example scenarios are datastore endpoint changing due a automated snapshot recovery or automated datastore credentials rotations or chaos testing. With the current design, spicedb will still report healthy accepting traffic, but still failing to process requests. There is no way for us to auto heal in these scenarios from the existing health check which is deep enough to ensure that spicedb is running and responding but not deep enough to ensure it is responding correctly.

Those cases should ideally be monitored by an external tool, as they are (with perhaps exception of the credentials rotating and maybe even then) a state change on the database side. In our experience, having the client report unhealthy when something changes on the service can easily lead to transient health check failures... and thus cause the entire set of clients to be replaced. We could add an additional health check that does report these statuses, but I would never recommend relying upon it for pod replacement for the reasons outlined above.
