### ISSUE TITLE
watch fell too far behind and was disconnected

### ISSUE THREAD

**Issue by razorness** [authzed/spicedb#928]
Hey people, I observed following behavior:

I programmed a servie which watches every mutation in spicedb and pushes these into kafka. When I bootstrap my SpiceDB instance with all my organizations, users and relations too quickly, the watching connection fails with `rpc error: code = ResourceExhausted desc = watch disconnected: watch fell too far behind and was disconnected` which I resume with last known ZedToken, which hopefully prevents me from missing mutation events.
When I add a sleep about 150 ms each write against spicedb, error is not getting thrown.

Setup:
- **Server**: SpiceDB `v1.13.0` single instance, running on Ubuntu 20.04.5 LTS
- **Datastore**: local PostgreSQL `v14.5-2.pgdg20.04+2`, connection via unix socket
- **Client**: `github.com/authzed/authzed-go v0.7.0`

**Comment by vroldanbet** [comment]
Hey @razorness, thanks for reporting!

The error you see happens when the consumers of Watch API are not reading changes fast enough, and the channel used for buffering fills up:

https://github.com/authzed/spicedb/blob/cb7b9569ce4b10caa1320dcb9ef16ce1aae7659b/internal/datastore/postgres/watch.go#L82-L87

The size of the buffer is by default 128 items, and all datastores can configure this value. Unfortunately it seems like we are missing a CLI flag to expose it:

https://github.com/authzed/spicedb/blob/b521828c0e42b5cacba5c30d468f0fec5e7b7392/pkg/cmd/datastore/datastore.go#L87

I think could expose and you could adjust it accordingly until it works well for your workload.

@josephschorr @jakedt any reason not to expose the watch API buffer size as a CLI option?

**Comment by vroldanbet** [comment]
@razorness improvements to Watch API performance and reliability, alongside [exposing the `WatchBufferLength`](https://github.com/authzed/spicedb/pull/1039/files#diff-54b805f6ef02ea3ea87934cfb51196977eb8ef1708c73b8941be872350bf68f2R126), were recently merged as part of https://github.com/authzed/spicedb/pull/1039

Kudos to @jakedt for all the work here ✨ 

These changes will be part of the next release, closing as fixed
